### ISSUE TITLE
[ROADMAP] - Implement a customized version of turnbattle 

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#12]
The turnbattle module from Evennia's contrib code might be a good baseline to create the custom RPG system for gridpunx. This could potentially save a lot of work compared to starting from scratch. Some research may be required before starting.

**Goals page**
[Pre-Alpha](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals)

**Checkbox Item(s)**
- Custom RPG system
  - [ ] Customized turn-based battle system

**Additional Requirements**
- None? (May need some more research)

**Closing Requirements**
- [ ] Write development documentation in the wiki
- [ ] Run basic tests
