### ISSUE TITLE
[ROADMAP] - Implement a Character object that ties into the custom RPG system

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#13]
Part of the RPG system will require a massive re-working of the `Character` object that represents a player's physical character. Note that the 'Advanced Health system' checkbox was excluded, since that will be a major change itself and have its own issue.

**Goals page**
[Relevant Goals Page](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals)

**Checkbox Item(s)**
- Custom RPG system
  - [ ] Special Character object that has various properties, functions, commandsets, and scripts which tie characters into the RPG mechanics.
    - [ ] Character creation system
    - [ ] Customized emote system
    - [ ] Custom inventory system

**Additional Requirements**
- None?

**Closing Requirements**
- [ ] Write development documentation in the wiki
- [ ] Run basic tests
