### ISSUE TITLE
[ROADMAP] - Add an advanced health system to the custom character object.

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#14]
The Advanced Health system for physical characters should feel somewhat like a modern survival-style game. A player will need to manage various aspects of their character's health beyond just a 'hitpoints' value. This could include things like hunger, thirst, different types of injuries, etc. Potentially, this could also include other things like diseases.

This has the potential to be a very large and complex feature to add, but is just a basic idea at this point. More research and planning is necessary before starting this task, and it may get scrapped entirely. Therefore, this should be the last element of the custom RPG system to be added.

**Goals page**
[Pre-Alpha Goals Page](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals)

**Checkbox Item(s)**
- Custom RPG system
  - Special Character object
    - [ ] Advanced Health system

**Additional Requirements**
- [ ] Complete planning/research.

**Closing Requirements**
- [ ] Write development documentation in the wiki
- [ ] Run basic tests
