### ISSUE TITLE
[ROADMAP] - Add a typeclass for mobile objects (mobs)

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#15]
Mobile objects (mobs) will be objects capable of moving around and interacting with the world themselves without needing to be moved or puppeted by a Game Master. They are differentiated from NPCs by their lack of a dialogue tree. However, it may be useful to utilize this feature and create a mobile NPC typeclass which combines the two.

Planned AI states:
- Passive -- Won't ever attack anything, and will run away if attacked. Mostly intended for friendly NPCs. Could be used for "sentient" scenery, like animals or filling rooms with activity.
- Provoke-able Apprehend -- Won't attack, but can be provoked to chase, capture and relocate the provoker.
- Apprehend -- Chase, capture and relocate a specific target.
- Provoke-able Hostile -- Won't attack, but can be provoked to fight.
- Hostile -- Will always attack.

**Goals page**
[Pre-Alpha Goals Page](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals)

**Checkbox Item(s)**
- Basic mob typeclasses
  - [ ] `RealMobileObject` generic typeclass for mobs with a simple AI.
  - [ ] Add a `RealMobileNPC` typeclass for mobile NPCs

**Additional Requirements**
- [ ] Add an even more generic `MobileObject` typeclass that can be reused for mobs in the digital realm.
- [ ] `RealSecurityGuard` NPC
- [ ] `RealHuman` typeclass for mobile humans 
- [ ] `RealRobot` typeclass for mobile machines

**Closing Requirements**
- [ ] Write development documentation in the wiki
- [ ] Run basic tests
