### ISSUE TITLE
[ROADMAP] - Add method(s) of transportation around the physical world.

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#16]
In rooms that are "outside," characters get harmed if they are just walking around. In order to avoid taking damage going from building to building, players should have at least one alternate method of transport that gives them protection from the outdoors. More research and planning is necessary.

Possible Ideas:
- Taxis
- Transport tubes that can take you directly to another building (like Futurama/Star Trek)
- Ventilation Shafts and/or Sewers that give less damage.

**Goals page**
[Pre-Alpha Goals Page](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals)

**Checkbox Item(s)**
- Add some slightly more advanced typeclasses for the physical realm
  - [ ] transportation method(s) -- method(s) of moving between buildings.

**Additional Requirements**
- [ ] Complete planning/research

**Closing Requirements**
- [ ] Write development documentation in the wiki
- [ ] Run basic tests
