### ISSUE TITLE
[ROADMAP] - Add a 'terminal' object that allows characters to access the digital realm.

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#17]
In order to access the digital realm, characters will need to interact with an object that has a connection to it. A 'terminal' will be that object. This task will need some major planning and research before starting.

**Goals page**
[Pre-Alpha Goals Page](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals)

**Checkbox Item(s)**
- Add some slightly more advanced typeclasses for the physical realm
  - [ ] terminal object -- object which allows for a grid connection.

**Additional Requirements**
- [ ] Complete planning/research

**Closing Requirements**
- [ ] Write development documentation in the wiki
- [ ] Run basic tests
