### ISSUE TITLE
[ROADMAP] - Add a CommandSet for commands related to skills

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#18]
Part of the custom RPG system will be a skill system. Most skills will have their own command, and they should all be collected into a CommandSet that is assigned to Characters. Note that this issue is solely focused on implementing the listed commands, and not the entire skill system. This is only one part of the skills system, and the RPG system changes to the Character object will probably be carried out first.

**Goals page**
[Pre-Alpha Goals Page](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals)

**Checkbox Item(s)**
- Custom RPG system
  - [ ] Custom CommandSet that contains all actions which utilize the RPG mechanics.
    - [ ] Status
    - [ ] Climb
    - [ ] Lift
    - [ ] Brawl
    - [ ] Learn
    - [ ] FirstAid
    - [ ] Repair
    - [ ] Haggle
    - [ ] Lie
    - [ ] Reason
    - [ ] Intuition
    - [ ] Sneak
    - [ ] Steal
    - [ ] Dodge

**Additional Requirements**
- Complete issue #13 

**Closing Requirements**
- [ ] Write development documentation in the wiki
- [ ] Run basic tests
