### ISSUE TITLE
[ROADMAP] - Add a typeclass for player-controlled characters in the digital realm.

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#19]
Players should be able to enter a 'digital ream' of the game's world. Instead of their flesh and blood character being transported into a computer (Tron style), a player will become (puppet) an object that is inside the digital realm while their Character object remains in the physical realm. The working name for the class is `DigitalPuppet`. Much more research and planning is needed for this, and will require implementing other features related to the game's digital realm. This may be implemented in tandem with issue (#17).

**Goals page**
[Pre-Alpha Goals Page](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals)

**Checkbox Item(s)**
- Special game mechanics
  - [ ] System of interaction that allows players to move a representation of themselves around in the digital realm while they're actual character remains in the physical realm.

**Additional Requirements**
- Complete issue #9 first

**Closing Requirements**
- [ ] Write development documentation in the wiki
- [ ] Run basic tests
