### ISSUE TITLE
[ROADMAP] - Implement a customized in-game time system.

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#20]
Using examples from Evennia's source code and documentation, a custom system for in-game time will be added to make the world more dynamic. The initial implementation will utilize a 4x time scale, so one in-game hour equals 15 minutes in real life. The intended purpose of the time system is not well defined yet. 

**Goals page**
[Pre-Alpha Goals Page](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals)

**Checkbox Item(s)**
- Special game mechanics
  - [x] Custom Game Time

**Additional Requirements**
- [x] Decide how time will affect the game's rules, world, and characters.

**Closing Requirements**
- [x] Write development documentation in the wiki
- [x] Run basic tests

**Comment by mfreidel** [comment]
Custom game time was changed to 4x IRL time with commit: https://github.com/gridpunx-team/gridpunx/commit/8e9ac9919ec08fa585d31e81da20a1d283a9d877

**Comment by mfreidel** [comment]
I'm debating whether or not I want to implement realistic sunrise and sunset times based on this calculation: (https://www.esrl.noaa.gov/gmd/grad/solcalc/solareqns.PDF). Alternatively, I could just use the 'astral' python package (https://pypi.org/project/astral/). Astral would make implementation a little easier and also allow for adding moon phases!

For now, I think I'm just going to have sunrise/sunsets occur at the same time every day (06:30 and 19:30).

**Comment by mfreidel** [comment]
Sunrise and sunset global script events were added in commit: https://github.com/gridpunx-team/gridpunx/commit/a83f67da422705350f3adc0daa099655f4bf46d0. A new server will need these to be started manually via in-game python, which isn't ideal.

Other game mechanics utilizing the game's time are likely to be highly situational, and will not be added in commits related to this issue. Time should probably be something to consider for most features added from now on.

**Comment by mfreidel** [comment]
Wiki page describing this new functionality was created here: https://github.com/gridpunx-team/gridpunx/wiki/World.
