### ISSUE TITLE
[ROADMAP] - Create foundations for economy system

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#21]
The economy will be a major gameplay element. It will actually be a fairly large and complex system that involves goods and services in both legitimate and black markets. Many of the components will be implemented later, but they will all need a foundation to build from. Namely, money. 

Initial currency planned:
1. Standard Currency (gridbits) -- Digital currency stored in a bank account value. Used for most transactions in both physical and digital realms.
2. Physical Money (physbits) -- Physical representation of the standard digital currency. Can be "deposited" and "withdrawn" from the account value. Mainly intended for black market transactions.

**Goals page**
[Pre-Alpha Goals Page](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals)

**Checkbox Item(s)**
- Special game mechanics
  - [ ] Custom Economy

**Additional Requirements**
- [ ] Research how to lump multiple identical objects into piles or stacks.
- [ ] A way to pay for things using digital currency in the physical realm.
- [ ] Implement an ATM object.

**Closing Requirements**
- [ ] Write development documentation in the wiki
- [ ] Run basic tests
