### ISSUE TITLE
[ROADMAP] Create room typeclasses for physical realm.

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#3]
Rooms are one of the basic building blocks of making a MUD's world, and an important part of establishing the setting. The idea here is to have an environment where exposure to the outside world is toxic by default. Buildings provide a climate controlled area that is safe to be in. Air-locks aren't required. 

This will require typeclasses for `physical_room`, `physical_room_outside`, `physical_room_inside`, and probably some sort of script that slowly harms the player while in an "outside" room.

**Goals page**
[Pre-Alpha Goals](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals)

**Checkbox Item(s)**
- [x] room objects
  - [x] `RealOutside` typeclass for outside areas
  - [x] `RealInside` typeclass for inside areas

**Additional Requirements**
- [x] `RealRoom` base typeclass
- [x] `HarshClimate` script that harms humans while outside

**Closing Requirements**
- [x] Write development documentation in the wiki
- [x] Run basic tests

**Comment by mfreidel** [comment]
This was feature was added with commit: https://github.com/gridpunx-team/gridpunx/commit/6d2edf5fc39eb44475f6571f4990f548789ba053

**Comment by mfreidel** [comment]
Details were added to the [Typeclasses](https://github.com/gridpunx-team/gridpunx/wiki/Typeclasses) page in the wiki.
