### ISSUE TITLE
[ROADMAP] - Create basic character typeclass

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#4]
Just a basic character typeclass to have something to work with, and to be modified later while more features are added. This might just be as simple as changing the typeclass name in the generated file (pure Evennia default character typeclass). Maybe something simple will be added as well. 

**Goals page**
[Pre-Alpha Goals](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals)

**Checkbox Item(s)**
- [x] Customize the `Character` typeclass

**Additional Requirements**
(None?)

**Closing Requirements**
- [x] Write development documentation in the wiki
- [x] Run basic tests

**Comment by mfreidel** [comment]
The default `Character` class seems necessary for Evennia. I'm going to leave it named how it is, and then just clearly distinguish the digital character with a separate class having no use of the word "Character" (probably: `DigitalPuppett` ). It will have to be noted that any reference to "Character" anywhere will be referring to the physical character.

**Comment by mfreidel** [comment]
Character typeclass was modified and pushed to the repo on github did some basic testing to make sure it worked properly and without errors. Added a Documentation page with the details of what I added. All checkboxes marked.
