### ISSUE TITLE
[ROADMAP] - Create simple object typeclasses

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#5]
Create a set of typeclasses for objects that can be held, objects that are part of the environment, and a general-purpose object type.

**Goals page**
[Pre-Alpha Goals](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals/_edit)

**Checkbox Item(s)**
- [x] Simple object typeclasses
  - [x] `RealObject` typeclass
  - [x] `RealItem` typeclass
  - [x] `RealEnvironment` typeclass
  - [x] `RealThing` typeclass

**Additional Requirements**
(None?)

**Closing Requirements**
- [x] Write development documentation in the wiki
- [x] Run basic tests

**Comment by mfreidel** [comment]
These will need to be new classes in `typeclasses/objects.py` which inherit the empty `Object` class with some special attributes set for each one.

**Comment by mfreidel** [comment]
Hierarchy established with commit: https://github.com/gridpunx-team/gridpunx/commit/6145fe508b442b9be9bd4a4d1685b1f22c6d37ec

**Comment by mfreidel** [comment]
I might want a few more generic typeclasses that distinguish different types of `RealThing`. For example: maybe a `RealSmallThing` class that is allowed to be picked up by players, and a `RealHeavyThing` which can only be picked up by a player (or multiple players) based on an attribute value.

**Comment by mfreidel** [comment]
Basic object properties and locks were defined for these classes in commit: https://github.com/gridpunx-team/gridpunx/commit/d0fab6c7a95441008c852b6c45c2fe083a44e18c

**Comment by mfreidel** [comment]
I had some misunderstandings about how inheritance works. I will need to rework some of the attributes I defined into functions in order for them to be properly inherited.

**Side note:** Testing this was a long and arduous process. I now feel the need to start writing unit tests so that I'm not fiddling around with manual testing in the world that I'm building.

**Comment by mfreidel** [comment]
Descriptions and basic information added to the wiki in the [Typeclasses](https://github.com/gridpunx-team/gridpunx/wiki/Typeclasses) page. This item is now complete.
