### ISSUE TITLE
[ROADMAP] - Create basic NPC typeclasses 

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#6]
Create typeclasses for generic, human, and robot NPCs.

**Goals page**
[Pre-Alpha Goals](https://github.com/gridpunx-team/gridpunx/wiki/Pre-Alpha-Goals)

**Checkbox Item(s)**
- Basic NPC typeclasses
  - [x] `RealTalkingNPC` generic typeclass for NPC objects with dialogue trees.
  - [x] NPC dialogue system -- a system to easily create dialogue for interacting with non-hostile NPCs.

**Additional Requirements**
- Unplanned items
  - [x] Usable NPC with a custom dialogue tree in public repo.

**Closing Requirements**
- [x] Write development documentation in the wiki
- [x] Run basic tests

**Comment by mfreidel** [comment]
NPC dialogue system was added with commit: https://github.com/gridpunx-team/gridpunx/commit/d744e28c889bbff3f963cc2862a83fc36283d497

The checkbox items may need to be redefined. This due to yet another misunderstanding about how I would implement this and how the engine works. Eventually, I'll have a good enough understanding of Evennia that I'll be able to develop a solid plan for Roadmap items from the start.

**Comment by mfreidel** [comment]
Documentation was added to the [Typeclasses wiki page](https://github.com/gridpunx-team/gridpunx/wiki/Typeclasses). This task is now complete.
