### ISSUE TITLE
[ROADMAP] - Add some baseline features for building in the physical realm.

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#7]
In order to properly build, interact with, and move around in the physical world, some baseline features need to be added.

**Goals page**
[Private Alpha Goals](https://github.com/gridpunx-team/gridpunx/wiki/Private-Alpha-Goals)

**Checkbox Item(s)**
- General Purpose builder tools
  - [ ] Builder menu
  - [ ] GameMaster menu
  - [ ] Prototypes and Spawners

**Additional Requirements**
- [ ] Make list of prototypes that would be useful to have.

**Closing Requirements**
- [ ] Write development documentation in the wiki
- [ ] Run basic tests
