### ISSUE TITLE
[ROADMAP] - Create access control for physical realm

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#8]
In order to allow players to have private rooms and other locked resources in the physical realm, an access control system will be needed.

**Goals page**
[Private Alpha Goals](https://github.com/gridpunx-team/gridpunx/wiki/Private-Alpha-Goals)

**Checkbox Item(s)**
- [ ] Basic access control system
  - [x] token -- an identity object that players carry around in the physical world. May be copied or stolen.

**Additional Requirements**
- [ ] Simple cryptographic authentication mechanism based on properties of the individual token.
- [x] A 'use' command that allows you to use objects with other objects.
- [x] Special exit typeclass with token authentication lock
- [x] Storage container with token authentication lock

**Closing Requirements**
- [ ] Write development documentation in the wiki
- [ ] Run basic tests
