### ISSUE TITLE
[ROADMAP] - Create simple digital realm typeclasses

### ISSUE THREAD

**Issue by mfreidel** [gridpunx-team/gridpunx#9]
Create some basic typeclasses that will be used in the digital realm.

**Goals page**
[Private Alpha Goals](https://github.com/gridpunx-team/gridpunx/wiki/Private-Alpha-Goals)

**Checkbox Item(s)**
- [ ] Basic typeclasses to use in the digital realm
  - [ ] grid_object typeclass -- Default object type for everything in the digital realm
  - [ ] grid_room typeclass -- Default object type for all rooms in the digital realm
  - [ ] talisman typeclass (and command?) -- a special type of grid_object that allows a player to interact with the digital realm.

**Additional Requirements**
- [ ] Decide whether talisman commands will be implemented now, or split off into another issue.

**Closing Requirements**
- [ ] Write development documentation in the wiki
- [ ] Run basic tests
